"""
signals.py — detection signals for Provenance Guard.

Signal 1 (this milestone): LLM-based semantic/stylistic assessment via Groq.
Signal 2 (Milestone 4): stylometric heuristics.
"""

import os
import json
from groq import Groq

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def llm_signal(text: str) -> dict:
    """
    Sends text to the Groq LLM and asks for a structured AI-likelihood
    assessment.

    Returns:
        {
            "score": float in [0.0, 1.0]  # 1.0 = strongly reads as AI-generated
            "rationale": str              # one-sentence explanation, for logs/appeals
        }
    """
    client = _get_client()

    prompt = f"""You are assessing whether a piece of writing was generated by AI \
or written by a human. Respond ONLY with valid JSON, no markdown fences, no \
preamble, in exactly this shape:

{{"score": <float between 0.0 and 1.0, where 1.0 means strongly AI-generated \
and 0.0 means strongly human-written>, "rationale": "<one sentence explaining \
your reasoning>"}}

Text to assess:
\"\"\"{text}\"\"\""""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        max_tokens=200,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()

    try:
        parsed = json.loads(raw)
        score = float(parsed["score"])
        score = max(0.0, min(1.0, score))  # clamp defensively
        rationale = parsed.get("rationale", "")
    except (json.JSONDecodeError, KeyError, ValueError, TypeError):
        # If the model doesn't return clean JSON, fail safe toward "uncertain"
        score = 0.5
        rationale = "Could not parse model response; defaulted to neutral."

    return {"score": score, "rationale": rationale}